# Generated by Django 5.1.2 on 2024-10-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='carmake',
            new_name='car_make',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_id',
        ),
    ]
